### ISSUE TITLE
Softmax problem

### ISSUE THREAD

**Issue by Google0007** [P2333/SCORE#1]
Hello, I would like to ask what is the function of the Softmax function in the toy_demo_1d.py file? Why can Softmax(X + delta) be used in the SCORE algorithm on line 97? Is this meant to represent a new data distribution?
Thanks in advance!

**Comment by P2333** [comment]
Hi, sorry for the late response.

Softmax(X + delta) is used to calculate the **data gradient**, in order to directly minimize R_{SCORE} (as formulated in Appendix B.2 of our paper). Note that in this toy demo we have closed-form access to the data distribution, such that we can precisely obtain the data gradient via back-propagation through Softmax(X + delta) w.r.t. delta.

In contrast, for practical data distribution (e.g., CIFAR-10) we cannot obtain the data gradient, so we need resort to the techniques described in Section 3.
